name: prod 서버 빌드배포

on:
  push:
    branches: [ "prod" ]

jobs:
  build:
    environment: prod
    runs-on: [self-hosted, macOS, ARM64]

    strategy:
      matrix:
        node-version: [22.14.0]

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        id: build-step
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: |
          pnpm build:prod || echo "BUILD_EXIT_CODE=$?" >> $GITHUB_ENV

      - name: slack-send failed
        if: failure() && env.BUILD_EXIT_CODE != '2'
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "⛔ PROD-ESG REPORT 빌드실패 알림",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "⛔ [PROD-ESG REPORT] 빌드실패\n ${{ job.status }}\n${{ github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: deploy to s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync --delete --region ap-northeast-2 --exclude "*.map" dist s3://customer-report.upbox.us

  invalidate-dev:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Invalidation Cloudfront
        env:
          SOURCE_PATH: './dist'
          AWS_REGION: 'ap-northeast-2'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DISTRIBUTION_ID: ${{ secrets.ESG_REPORT_DISTRIBUTION_ID }}
        run: |
          aws cloudfront create-invalidation --distribution-id ${{secrets.ESG_REPORT_DISTRIBUTION_ID}} --paths "/*"
      - name: slack-send completed
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "✅ PROD-ESG REPORT 배포완료 알림",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "✅ [PROD-ESG REPORT] 배포완료\n ${{ job.status }}\n${{ github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK